services:
  - type: web
    name: space-portfolio
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Cache-Control
        value: max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
